#pragma once

#define DEVI_UNIFORM_SKYBOX 0u
#define DEVI_UNIFORM_ALBEDOMAP 0u
#define DEVI_UNIFORM_SPECULARMAP 1u
#define DEVI_UNIFORM_NORMALMAP 2u

#define DEVI_UNIFORM_ROUGHNESSMAP 1u	//PBR
#define DEVI_UNIFORM_AOMAP 3u
#define DEVI_UNIFORM_METALLICMAP 4u
#define DEVI_UNIFORM_DEPTHMAP 5u

#define DEVI_UNIFORM_HEIGHTMAP 6u